### PR TITLE
Make the Parameter object not abstract

### LINKED ISSUE #8: Swagger\Object\PathItem::getParameters gives fatal error
Swagger\Object\PathItem::getParameters gives fatal error "Cannot instantiate abstract class Swagger\Object\Parameter"

Can I create a pull request for you, changing:

``` php
abstract class Parameter extends AbstractObject
```

to

``` php
class Parameter extends AbstractObject
```

### PR DESCRIPTION
**Pull request by gisostallenberg**
Fixes #8

### CODE REVIEW

**Comment by gisostallenberg** [comment]
The check fails in a job that is not required to run, see #10. I can rebase this after you pulled #11

**Comment by TheFrozenFire** [comment]
Thanks for that. I should probably write some more unit tests. :)

**Comment by gisostallenberg** [comment]
Will you release the changes in near future?

**Comment by TheFrozenFire** [comment]
Done. These changes should be in 2.0.4 now.

**Comment by TheFrozenFire** [comment]
Done. These changes should be in 2.0.8 on this repo, and 2.0.4 on the client repo now.

**Pull request merged**
